package create;// Generated by Selenium IDE

import common.TestBase;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class CreateTaskTest extends TestBase {

    @Before
    public void login() {
        setup();
    }


    @Test
    public void createTaskTest() {
        appManager.getTodoHelper().createTask(
                new TaskData(
                        "Test",
                        "test"
                )
        );
    }

    @After
    public void logout() {
        appManager.getTodoHelper().logout();
    }
}
