// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @Test
  public void test() {
    driver.get("http://todolist.ru/");
    driver.manage().window().setSize(new Dimension(1792, 1010));
    driver.findElement(By.linkText("Вход")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("d23.alexandr");
    driver.findElement(By.id("user_password")).sendKeys("Test1");
    driver.findElement(By.id("user_password")).click();
    driver.findElement(By.cssSelector(".submit")).click();
  }
}
