package tests;// Generated by Selenium IDE

import common.TestBase;
import model.TaskData;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.testng.Assert;

public class CreateTaskTest extends TestBase {

    @Before
    public void login() {
        setup();
    }


    @Test
    public void createTaskTest() {
        int sizeBefore = appManager.getTodoHelper().createTask(
                new TaskData(
                        "Test",
                        "test"
                )
        );
        int sizeAfter = appManager.getTodoHelper().getSizeAfter();
        Assert.assertEquals(sizeBefore + 1, sizeAfter);
    }

    @After
    public void logout() {
        appManager.getTodoHelper().logout();
    }
}
