package tests;// Generated by Selenium IDE

import common.TestBase;
import model.UserData;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class SignInTest extends TestBase {

    @Before
    public void before() {
        setup();
    }

    @Test
    public void signIn() {
        getLoginHelper().login(new UserData(
                "d23.alexandr",
                "Test1"
        ));
        Assert.assertEquals("http://todolist.ru/todolist/index.html", getLoginHelper().getCurrentUrl());
    }

    @After
    public void logout() {
        appManager.getTodoHelper().logout();
    }

}
